#!/usr/bin/php
<?php

// Remote host
$remote = isset($argv[1]) ? $argv[1] : '10.0.0.1';

`ssh starkit@$remote ./env/stop.sh`;
`ssh starkit@$remote ./env/boot.sh`;

system("ssh starkit@$remote ./env/out.sh");
