#!/usr/bin/php
<?php

if (count($argv) < 2) {
    die("Usage: ./wifi field [host]\n");
}

// Remote host
$field = $argv[1];
$remote = isset($argv[2]) ? $argv[2] : '10.0.0.1';
$wiface = 'wlan0';

function cmd($cmd) {
    global $remote;
    $result = trim(`rhio $remote $cmd`);
    return $result;
}

$result = explode('=', cmd('/referee/teamId'));

//Configuration
$ESSID = 'HL_FIELD_'.strtoupper($field).'_5G';
$teamId = $result[1];

//Retrieve robot hostname
$hostname = trim(`ssh starkit@$remote cat /etc/hostname`);

//Set ip address
$ip = null;

// XXX: To update
$ipPrefix = '192.168.9.';

if ($hostname == 'olive') {
    $ip = $ipPrefix.'41';
} else if ($hostname == 'nova') {
    $ip = $ipPrefix.'42';
} else if ($hostname == 'arya') {
    $ip = $ipPrefix.'43';
} else if ($hostname == 'tom') {
    $ip = $ipPrefix.'44';
} else if ($hostname == 'rush') {
    $ip = $ipPrefix.'45';
} else {
    echo "\e[31mUnknown hostname:\e[m $hostname\n";
    die;
}

echo "Connecting \e[1m$hostname\e[m to wifi \e[1m$ESSID\e[m with IP \e[1m$ip\e[m (TeamId: \e[1m$teamId\e[m)\n";

//Wifi magic
`ssh starkit@$remote sudo killall -2 ping 2> /dev/null`;

// Be sure wpa supplicant is killed
`ssh starkit@$remote sudo killall -2 wpa_supplicant 2> /dev/null`;
`ssh starkit@$remote sudo killall -9 wpa_supplicant 2> /dev/null`;

// Down then upping the interface
`ssh starkit@$remote sudo ifconfig $wiface down`;
`ssh starkit@$remote sudo ifconfig $wiface up`;

// Joining the ESSID
//`ssh starkit@$remote sudo iw dev $wiface scan | grep $ESSID`;
`ssh starkit@$remote sudo iw $wiface connect $ESSID`;

// Setting IP address
`ssh starkit@$remote sudo ifconfig $wiface $ip netmask 255.255.0.0`;

// Connecting to WiFi
`ssh starkit@$remote "wpa_passphrase $ESSID humanoid2018 > /tmp/wpa.conf"`;
`ssh starkit@$remote sudo wpa_supplicant -B -i$wiface -c/tmp/wpa.conf -Dwext`;

// Open Iran
#`ssh starkit@$remote sudo ifconfig $wiface $ip netmask 255.255.255.0`;
#`ssh starkit@$remote sudo ifconfig wlan0 $ip netmask 255.255.255.0`;
//`ssh rstarkit@$remote "wpa_passphrase $ESSID humanoidrobot > /tmp/wpa.conf"`;
// OPen IRAN
#`ssh starkit@$remote "wpa_passphrase $ESSID Humanoid2018 > /tmp/wpa.conf"`;
#`ssh starkit@$remote sudo wpa_supplicant -B -i$wiface -c/tmp/wpa.conf -Dwext`;
sleep(3);

//Check to ping to router twice
echo "Check wifi by pinging router:\n";
$checkPing = `ssh starkit@$remote ping -W 1 -n -c 2 192.168.1.100`;

if (strpos($checkPing, '2 received, 0% packet loss')) {
    echo "\e[1mOK. Network is ready.\e[m\n";
} else {
    echo "\e[31mNetwork configuration failed:\e[m\n$checkPing\n";
    die;
}

//Check if RhobanServer listen to the referee
$isServerRunning = `ssh starkit@$remote ps aux | grep -v "grep" | grep "StarkitServer"`;
if (strpos($isServerRunning, 'StarkitServer')) {
    echo "StarkitServer is running. Check referee state:\n";
    $result = trim(`rhio $remote /referee/state`);
    echo "$result\n";
} else {
    echo "StarkitServer is not running.\n";
    die;
}

